# IKEv2 + EAP-MSCHAPv2，仅服务端证书；@SERVER_ID@ 由 install.sh 替换（须与证书 SAN/CN 及客户端填写地址一致）
connections {

  ikev2-eap {
    version = 2
    local_addrs = %any
    proposals = aes256-sha256-modp2048,aes128-sha256-modp2048,aes256-sha1-modp2048,aes128-sha1-modp2048

    pools = ikev2-v4
    send_cert = always
    reauth_time = 28800s
    fragmentation = yes

    local {
      auth = pubkey
      id = @SERVER_ID@
      certs = vpn-server-cert.pem
    }
    remote {
      auth = eap-mschapv2
      eap_id = %any
    }
    children {
      net {
        local_ts = 0.0.0.0/0
        remote_ts = 0.0.0.0/0
        esp_proposals = aes128gcm16-aes256gcm16-chacha20poly1305-default
      }
    }
  }
}

pools {
  ikev2-v4 {
    addrs = 10.0.2.2-10.0.2.201
  }
}
